# Generated by Django 5.2.13 on 2026-04-20 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='GallerySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='3D Photography Portfolio', max_length=100)),
                ('hero_title', models.CharField(default='Capturing Moments in 3D', max_length=200)),
                ('hero_subtitle', models.TextField(default='Explore my work through an immersive 3D gallery')),
                ('photographer_name', models.CharField(default='Jane Doe', max_length=100)),
                ('photographer_bio', models.TextField(blank=True)),
                ('email', models.EmailField(default='contact@example.com', max_length=254)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('camera_settings', models.CharField(blank=True, help_text='e.g., f/2.8, 1/500s, ISO 100', max_length=200)),
                ('date_taken', models.DateField(default=django.utils.timezone.now)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.category')),
            ],
            options={
                'ordering': ['order', '-date_taken'],
            },
        ),
    ]
