# Generated by Django 5.2.13 on 2026-04-20 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_blogpost_booking_clientgallery_clientphoto_package_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='photograph',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='photograph',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='date',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.package'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fa-camera', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientphoto',
            name='image',
            field=models.ImageField(upload_to='client_galleries/'),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.category'),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(default='New York, NY'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='behind_scene_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(default='hello@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='google_map_embed',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(default='+1 (555) 123-4567', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='photographer_bio',
            field=models.TextField(default='Award-winning photographer with 8+ years of experience.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
