# Generated by Django 5.2.13 on 2026-04-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_clientgallery_client_alter_clientgallery_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientgallery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='clientgallery',
            name='access_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='clientphoto',
            name='image',
            field=models.ImageField(upload_to='client_galleries/%Y/%m/'),
        ),
    ]
