# Generated by Django 5.2.13 on 2026-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_clientgallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientgallery',
            name='access_code_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='clientgallery',
            name='current_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientgallery',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientgallery',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientgallery',
            name='max_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientphoto',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('access_code', models.CharField(blank=True, max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'attempted_at'], name='gallery_acc_ip_addr_7c0e94_idx')],
            },
        ),
    ]
